# ***********[ PyTorch ]********

In [1]:
import torch as t

In [36]:
a=t.tensor([1,2,3,4,5])
b=t.tensor([6,7,8,9,10])
a+b

tensor([ 7,  9, 11, 13, 15])

In [37]:
b-a

tensor([5, 5, 5, 5, 5])

In [38]:
b*a

tensor([ 6, 14, 24, 36, 50])

In [39]:
b/a

tensor([6, 3, 2, 2, 2])

In [40]:
b//a

tensor([6, 3, 2, 2, 2])

In [41]:
b%a

tensor([0, 1, 2, 1, 0])

In [42]:
b**a

tensor([     6,     49,    512,   6561, 100000])

## Indexing

In [2]:
a=t.tensor([1,2,3,4,5])
b=t.tensor([6,7,8,9,10])
a[0]

tensor(1)

In [44]:
a[:10]   # print start to end bcoz till 10th index ,but we have only till 4th index  so print it

tensor([1, 2, 3, 4, 5])

In [45]:
a[10:]   # out last index in 4, we want from 10 so no elemnt , so print empty tensor

tensor([], dtype=torch.int64)

In [46]:
a[-1]  # print last elmnt , bcoz indexing from last start frm -1

tensor(5)

In [47]:
a[-1:]  # start from last end to last, last is last so only 5

tensor([5])

In [48]:
a[-1:4]  # indexing not work in reversing

tensor([], dtype=torch.int64)

In [49]:
a[-1:-3]  # reverse indexing not workbcoz bydefault 1 increment so , so print only [] tensor

tensor([], dtype=torch.int64)

In [3]:
a[-1:-3:-1] # negative step not working

ValueError: negative step not yet supported

In [ ]:
a=t.tensor([1,2,3,4,5])
b=t.tensor([6,7,8,9,10])

In [ ]:
a==b

In [ ]:
a!=b

In [ ]:
a>b

In [ ]:
b>a

In [ ]:
b>>a

In [ ]:
a<<b

In [ ]:
a is b

In [ ]:
a in b

## Shape

In [ ]:
a=t.tensor(10)
b=t.tensor((1,2,3))
c=t.tensor(([3,4,5]))
d=t.tensor([(1,2,3)])
e=t.tensor([[3,4,5]])
f=t.tensor([[[1,2,3],[4,5,6]]])
g=t.tensor([([[1,2,3],[4,5,6]])])
h=t.tensor([[([1,2,3],[4,5,6])]]) # at last ([]) treat as [[]] 2D tensor so
i=t.tensor([[([(1,2,3)],[(4,5,6)])]]) # ([()]=[[[]]])
i

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
c.shape

In [ ]:
d.shape

In [ ]:
e.shape

In [ ]:
f.shape  # 3D tensor

In [ ]:
g.shape

In [ ]:
h.shape

In [ ]:
i.shape

# Scalar

In [7]:
a=t.tensor(0)
a

tensor(0)

In [31]:
a=t.tensor(True)
a

tensor(True)

In [106]:
b=t.tensor(10)  # only one value, more than one value give error
b

tensor(10)

In [5]:
c=t.tensor(10,20)  # for scalar one argument except, more than one give u error
c

TypeError: tensor() takes 1 positional argument but 2 were given

In [8]:
a.shape  # bcoz scalar

torch.Size([])

In [10]:
a.data

tensor(0)

In [14]:
a.size()

torch.Size([])

In [15]:
a.dtype

torch.int64

# Not support in Torch

In [36]:
t.tensor([None])  # None data type not support

RuntimeError: Could not infer dtype of NoneType

In [103]:
a=t.tensor([1,2,3,4])
a.itemsize

AttributeError: 'Tensor' object has no attribute 'itemsize'

In [4]:
a=t.tensor(['a','p']) # String doesn't support in torch
a

ValueError: too many dimensions 'str'

In [81]:
a=t.tensor([1+2j])  # torch not support complex
a

RuntimeError: Could not infer dtype of complex

In [83]:
a=t.tensor({1,2,3})  # set not support in Torch

RuntimeError: Could not infer dtype of set

In [86]:
a=t.tensor([[1],3,4])  # torch not support "Object" data type

TypeError: not a sequence

In [91]:
a=t.tensor([1,2,3])
a.astype(float)

AttributeError: 'Tensor' object has no attribute 'astype'

# Vector or 1D Tensor

In [18]:
a=t.tensor((1,2,3))
a

tensor([1, 2, 3])

In [35]:
a=t.tensor([1,1.2,True])
b=t.tensor([4,5.2,False])
print(a)
b

tensor([1.0000, 1.2000, 1.0000])


tensor([4.0000, 5.2000, 0.0000])

In [95]:
b=t.tensor([4,5,6])
b

tensor([4, 5, 6])

In [97]:
c=t.arange(10)
c

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a.dtype

torch.int64

In [19]:
a.shape

torch.Size([3])

In [21]:
a.data

tensor([1, 2, 3])

In [23]:
a.ndim

1

In [25]:
a.size()

torch.Size([3])

# 2D tensor

In [29]:
a=t.tensor([(1,2,3)])
a

tensor([[1, 2, 3]])

In [42]:
a=t.tensor([(1,2,3,True,False)])
print(a)
a.dtype

tensor([[1, 2, 3, 1, 0]])


torch.int64

In [46]:
b=t.arange(10).reshape(2,5)
print(b)
print(b.shape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.Size([2, 5])


In [48]:
a=t.tensor([[1,2,3],[4,5,6]],dtype=t.float)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [51]:
a=t.tensor([[True,0,3],[False,5,6]],dtype=t.bool)
a

tensor([[ True, False,  True],
        [False,  True,  True]])

In [53]:
a.ndim

2

In [55]:
a.data

tensor([[ True, False,  True],
        [False,  True,  True]])

In [57]:
a.shape

torch.Size([2, 3])

In [59]:
a.size()

torch.Size([2, 3])

# 3D Tensor

In [61]:
a=t.tensor([[[1,2,3],[4,5,6]]])
a

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [63]:
b=t.tensor([[(1,2,3),(4,5,6)]])
b

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [67]:
c=t.arange(9).reshape(1,3,3)
c

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

In [69]:
a.ndim

3

In [71]:
a.shape

torch.Size([1, 2, 3])

In [73]:
a.data

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [75]:
a.size()

torch.Size([1, 2, 3])

# Transposition

In [109]:
a=t.tensor([(1,2,3),(4,5,6)])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [111]:
a.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [114]:
b=t.transpose(a,-1,0)  #(-1,0) by default range for transpose
b

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [116]:
a.shape

torch.Size([2, 3])

In [118]:
b.shape

torch.Size([3, 2])

In [6]:
c=t.tensor([[[1,2],[3,4],[5,6]]])
c

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [125]:
a=c.T
a

tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])

In [8]:
a=t.transpose(c,-2,0)
a

tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]])

In [9]:
a=t.transpose(c,-1,0)
a

tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])

In [10]:
a=t.transpose(c,-2,-1)
a

tensor([[[1, 3, 5],
         [2, 4, 6]]])

In [132]:
c.shape

torch.Size([1, 3, 2])

In [134]:
a.shape   # shape reversed by transpose

torch.Size([2, 3, 1])

In [136]:
a=t.tensor([[[[1,2,3],[4,5,6]]]])
a

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [139]:
b=a.T
b

tensor([[[[1]],

         [[4]]],


        [[[2]],

         [[5]]],


        [[[3]],

         [[6]]]])

In [156]:
c=a.transpose(-1,0)
c

tensor([[[[1],
          [4]]],


        [[[2],
          [5]]],


        [[[3],
          [6]]]])

In [141]:
a.shape

torch.Size([1, 1, 2, 3])

In [153]:
b.shape   # reverse the dimension

torch.Size([3, 2, 1, 1])

In [157]:
c.shape

torch.Size([3, 1, 2, 1])

# Addition

#### u can add 2 Tensor, both have tensor not other type

In [168]:
a=t.tensor(10)
b=t.tensor(20)
print(a+b)
a.add(b)

tensor(30)


tensor(30)

In [169]:
a+4

tensor(14)

In [174]:
a=t.tensor([10,11,12])
b=t.tensor([1,2,3])
a+b

tensor([11, 13, 15])

In [172]:
b+[1,2,3]  # both have to be Tensor

TypeError: add(): argument 'other' (position 1) must be Tensor, not list

In [177]:
a=t.tensor([[[7,8,9],[10,11,12]]])
b=t.tensor([[[1,2,3],[4,5,6]]])
a+b

tensor([[[ 8, 10, 12],
         [14, 16, 18]]])

In [180]:
a=t.tensor([[[1,2,3]]])  
b=t.tensor([[[1,2,3],[4,5,6]]])
a+b  # add "a" to each row of "b"

tensor([[[2, 4, 6],
         [5, 7, 9]]])

# Broadcasting

#### how arrays are treated with different shapes during arithmetic operations

In [175]:
a=t.tensor(10)
b=t.tensor([1,2,3])
a+b

tensor([11, 12, 13])

In [178]:
a=t.tensor(10)
b=t.tensor([[[1,2,3],[4,5,6]]])
a+b  # add "a" to each element of "b"

tensor([[[11, 12, 13],
         [14, 15, 16]]])

In [181]:
a=t.tensor([1,2,3])  # need saome no for add in 2D tensor to 3D tensor
b=t.tensor([[[1,2,3],[4,5,6]]])
a+b  # add "a" to each row of "b"

tensor([[[2, 4, 6],
         [5, 7, 9]]])

In [187]:
a=t.tensor([[1,2,3]])  # need 'one' are same no of element for add in 2D tensor to 3D tensor
b=t.tensor([[[1,2,3],[4,5,6]]])
a+b  # add "a" to each row of "b"

tensor([[[2, 4, 6],
         [5, 7, 9]]])

In [189]:
a=t.tensor([[1,2,3],[4,5,6]])
b=t.tensor([[[10]],[[20]]])
a+b  # we got 2 tensor, first [10] add with "a", and 2nd add with [20]

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[21, 22, 23],
         [24, 25, 26]]])

# trace

In [191]:
a=t.tensor([(1,2),(3,4)])
a

tensor([[1, 2],
        [3, 4]])

In [194]:
a.trace()

tensor(5)

In [201]:
a=t.tensor([[1,2,3],[4,5,6]])
print(a)
t.trace(a)  # trace start from starting elemnt if tensor is not complete tensor 

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor(6)

#### Trace product

In [220]:
a=t.tensor([[1,2],[5,6]])
b=t.tensor([[4,5],[8,9]])
print(a@b)
# print(t.mm(a,b))  # .mm means matrix multiplication
print(t.trace(a@b))

tensor([[20, 23],
        [68, 79]])
tensor(99)


In [218]:
a=t.tensor([10])
b=t.tensor([2])
a.dot(b)  # .dot , support only for 1D tensor product  # if got product 2X2 then u got erro

tensor(20)