# Universal functions

In [3]:
import torch as t

In [ ]:
a=t.rand((2,2))
a

tensor([[0.6504, 0.6775],
        [0.9283, 0.2709]])

In [ ]:
b=t.randn((2,2))
b

tensor([[ 0.0885,  0.5305],
        [-0.0991,  0.2655]])

In [ ]:
t.random.random((2,3))

AttributeError: ignored

In [ ]:
a=t.rand((4,4))
a

tensor([[0.8436, 0.4253, 0.8911, 0.1314],
        [0.4452, 0.1913, 0.8537, 0.5600],
        [0.4635, 0.4139, 0.4573, 0.8944],
        [0.4906, 0.1030, 0.4956, 0.3555]])

## sum

In [ ]:
print(t.sum(a))

tensor(8.0152)


In [ ]:
a.sum(axis=0)

tensor([2.2428, 1.1335, 2.6977, 1.9412])

In [ ]:
a.sum(axis=1)

tensor([2.2914, 2.0502, 2.2290, 1.4446])

## min

In [ ]:
a.min()

tensor(0.1030)

In [ ]:
print(a.min(axis=0))  # also print value with its indexes

torch.return_types.min(
values=tensor([0.4452, 0.1030, 0.4573, 0.1314]),
indices=tensor([1, 3, 2, 0]))


In [ ]:
a.min(axis=1)

torch.return_types.min(values=tensor([0.1314, 0.1913, 0.4139, 0.1030]), indices=tensor([3, 1, 1, 1]))

## Max

In [ ]:
a

tensor([[0.8436, 0.4253, 0.8911, 0.1314],
        [0.4452, 0.1913, 0.8537, 0.5600],
        [0.4635, 0.4139, 0.4573, 0.8944],
        [0.4906, 0.1030, 0.4956, 0.3555]])

In [ ]:
a.max()

tensor(0.8944)

In [ ]:
print(a.max(axis=0))  # with max also print its correpondece index also

torch.return_types.max(
values=tensor([0.8436, 0.4253, 0.8911, 0.8944]),
indices=tensor([0, 0, 0, 2]))


In [ ]:
print(a.max(axis=1))

torch.return_types.max(
values=tensor([0.8911, 0.8537, 0.8944, 0.4956]),
indices=tensor([2, 2, 3, 2]))


## Cumlative sum

In [ ]:
a=t.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# cumsum accord to column wise
print(a.cumsum(axis=0))   # both are same bcoz (col,row)=(0,1) 
print(a.cumsum(axis=-2))  # (col,row)=(-2,-1)
# its 2D array so find out its vice versa axis for same outpit subtract 2 from axis


tensor([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]])
tensor([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]])


In [ ]:
# cumsum accord to row wise
print(a.cumsum(axis=1))
print(a.cumsum(axis=-1))

tensor([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]])
tensor([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]])


## cumlative product

In [ ]:
b=t.tensor([[1,2,3],[4,5,6],[7,8,9]])
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# cumltv product accord to column wise
print(b.cumprod(axis=0))
b.cumprod(axis=-2)

tensor([[  1,   2,   3],
        [  4,  10,  18],
        [ 28,  80, 162]])


tensor([[  1,   2,   3],
        [  4,  10,  18],
        [ 28,  80, 162]])

In [ ]:
# cumltv product accord to rows wise
print(b.cumprod(1))
b.cumprod(-1)

tensor([[  1,   2,   6],
        [  4,  20, 120],
        [  7,  56, 504]])


tensor([[  1,   2,   6],
        [  4,  20, 120],
        [  7,  56, 504]])

# Exponential $(e^x)$

In [ ]:
t.range(4,12)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
a=t.arange(2,dtype=t.int)
b=t.range(0,7,dtype=t.float)
a
print(a)
b

tensor([0, 1], dtype=torch.int32)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [ ]:
print(t.exp(b))

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03])


In [ ]:
print(t.exp(a))

RuntimeError: ignored

## ALL & ANY

#### ONly support for boolean data type only

In [ ]:
# ALL value True then "True" otherwise false
a=t.tensor([(True,True),(True,False)])
t.all(a)

tensor(False)

In [ ]:
a=t.tensor([(True,True),(True,True)])
t.all(a)

tensor(True)

In [ ]:
# ANY value in True then "TRUE", only when all r false thn "False"

In [ ]:
a=t.tensor([(True,True),(True,False)])
t.any(a)

tensor(True)

In [ ]:
a=t.tensor([(False,False),(False,False)])
t.any(a)

tensor(False)

# nan (None)

In [ ]:
a=t.tensor([t.nan,1,2])
t.nan(a)

AttributeError: ignored

In [ ]:
a=t.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
t.apply_along_axis(a)

AttributeError: ignored

### Argmax

In [ ]:
a=t.tensor([[1,8,3],[4,0,6],[7,8,1]])
a

tensor([[1, 8, 3],
        [4, 0, 6],
        [7, 8, 1]])

In [ ]:
# print max valie index
a.argmax()   # 7 means ,if we start elmnt from start with index 0, then 7th index value is maximum

tensor(7)

In [ ]:
# max elmnt for each column
a.argmax(axis=0)

tensor([2, 2, 1])

In [ ]:
#  max elmnt for each rows
a.argmax(1)   # 1 means axis=1

tensor([1, 2, 1])

In [4]:
c=t.arange(18).reshape(2,3,3)
c

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [5]:
c.argmax()

tensor(17)

In [ ]:
# if there r we have only 1 array then we got 0,0,0 like this., bcoz each elemnt comapre himself for [axis=0]
c.argmax(axis=0) # 0 comapre to 9  1 to 10 so bcox axis=0 means every elemtn for self array
# but there r we have 2 array so we comapring with correspondence index of 2nd array

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [6]:
# in 3D array, axis=1 means "Column wise"
# findout for each column max elmnt for seprate array index, so we got 6 indexes
# [0,3,6] 1st column,  [1,4,7] 2nd column and [9,12,15] like this we compare indexes indexing compare
c.argmax(1) 

tensor([[2, 2, 2],
        [2, 2, 2]])

In [7]:
# in 3D array, axis=2 means "Row wise"
# findout for each rows max elmnt for both seprate array index, so we got 6 indexes
# [0,1,2] 1st row,  [3,4,5] 2nd row like this indexing compare 
c.argmax(2)

tensor([[2, 2, 2],
        [2, 2, 2]])

## Argmin

In [10]:
b=t.tensor([[[44,56,13],[14,15,26],[22,12,33]]])
b

tensor([[[44, 56, 13],
         [14, 15, 26],
         [22, 12, 33]]])

In [11]:
b.argmin()    # 7 means, min elemnt find at 7 possition

tensor(7)

In [12]:
b.argmin(axis=0)  3 every elmnt comparre himself so we got all zero

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [13]:
b.argmin(axis=1)  # accord to each column wise

tensor([[1, 2, 0]])

In [14]:
b.argmin(axis=2)  # accord to each rows wise

tensor([[2, 0, 1]])

In [4]:
c=t.arange(18).reshape(2,3,3)
c

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [25]:
# mim elemnt index return
print(c.argmin())  # same put all elmnt in a row , index from 0 , n return min elmnt index

tensor(0)


In [29]:
# if there r we have only 1 array then we also got 0,0,0 like this., bcoz each elemnt comapre himself for [axis=0]
c.argmin(axis=0) # 0 comapre to 9  1 to 10 so bcox axis=0 means every elemtn for self array
# but there r we have 2 array so we comapring with correspondence index of 2nd array

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [41]:
# in 3D array, axis=1means "Column wise"
# findout for each column max elmnt for seprate array index, so we got 6 indexes
# [0,3,6] 1st column,  [1,4,7] 2nd column and [9,12,15] like this we compare indexes indexing compare
c.argmin(axis=1)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [5]:
# in 3D array, axis=2 means "Row wise"
# findout for each rows max elmnt index so we got 6 indexes
# [0,1,2] 1st rows,  [3,4,5] 2nd rows, [9,10,11]  like this indexing compare
c.argmin(axis=2)  # every elmnt of each row is minimum

tensor([[0, 0, 0],
        [0, 0, 0]])

## Argsort

In [7]:
a=t.tensor([1,5,4,88,14,6])
a.argsort()  # show index accord to its value in increasing order

tensor([0, 2, 1, 5, 4, 3])

In [32]:
b=t.tensor([[10,5,78],[1,108,98],[90,72,2]])
print(b)

tensor([[ 10,   5,  78],
        [  1, 108,  98],
        [ 90,  72,   2]])


In [33]:
b.argsort()  # byfefault "row wise" agrgumnt sorting, like axis=1 also same as

tensor([[1, 0, 2],
        [0, 2, 1],
        [2, 1, 0]])

In [35]:
# row wise argumnt sorting
b.argsort(axis=1)  # its look like Default argmnt sorting without given axis

tensor([[1, 0, 2],
        [0, 2, 1],
        [2, 1, 0]])

# bug in argsort

In [24]:
b.argsort(axis=0)  # bcoz 98>78 so i not got correct output
# if i replace 98 with less than 78 , thn i got correct output

tensor([[1, 0, 2],
        [0, 2, 0],
        [2, 1, 1]])

In [26]:
b=t.tensor([[10,5,78],[1,108,68],[90,72,2]])
print(b)

tensor([[ 10,   5,  78],
        [  1, 108,  68],
        [ 90,  72,   2]])


## we got correct output

In [27]:
# column wise argsorting
b.argsort(axis=0)

tensor([[1, 0, 2],
        [0, 2, 1],
        [2, 1, 0]])