# Universal Functions

In [3]:
import torch as t
import seaborn as sns
import matplotlib.pyplot as plt

## Average
#### not working in Pytorch bcoz "Mean" also do the same so

In [18]:
a=t.arange(13)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
t.average(a)

AttributeError: module 'torch' has no attribute 'average'

## Bincount
#### it support only 1D tensor

In [26]:
a=t.arange(5,25)  # 1D tensor
a

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24])

In [30]:
a.bincount() # bincount start from 0 index, those value not present it in till the range put 0 instead of it

tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1])

In [32]:
t.bincount(t.arange(5,50,2))  # bcoz step=2 so take altenate no.

tensor([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1])

In [36]:
a=t.tensor([[4,5,6],[7,8,9]])  # not supported 2D tensor , only support 1D tensor
a.bincount()

RuntimeError: bincount only supports 1-d non-negative integral inputs.

## Ceil

In [39]:
# print nearest greatest value 
a=t.tensor([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.2])
a.ceil()

tensor([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [41]:
a=t.tensor([[-1.7,1.5],[2.2,-0.5]])
a.ceil()

tensor([[-1.,  2.],
        [ 3., -0.]])

## Floor

In [201]:
# return nearest smallest value
a=t.tensor([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.2])
a.floor()

tensor([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [202]:
a=t.tensor([[-1.7,1.5],[2.2,-0.5]])
a.floor()

tensor([[-2.,  1.],
        [ 2., -1.]])

## clip Not working replace by
## Clamp

#### 1D tensor

In [115]:
a=t.arange(25)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [88]:
t.clamp(a,2,10)

tensor([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10])

# ??? DOUBT

In [116]:
t.clamp(a,15,10)

tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10])

In [92]:
t.clamp(a,12,10)

tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10])

In [94]:
t.clamp(a,24,10)

tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10])

In [96]:
t.clamp(a,25,10)

tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 25])

In [98]:
t.clamp(a,28,10)

tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 28])

## ------------------------------------

#### 2D tensor

In [120]:
a=t.tensor([[24,40],[10,55]])
print(a)
t.clamp(a,25,35)

tensor([[24, 40],
        [10, 55]])


tensor([[25, 35],
        [25, 35]])

In [118]:
# 1st  perform value less than 45(exclude) beacome 45, then perform value>30 become 30
t.clamp(a,45,35)

tensor([[45, 45],
        [45, 35]])

In [124]:
t.clamp(a,55,35)

tensor([[55, 55],
        [55, 35]])

## conjugate
#### used for changing the sign of imaginary value of complex no
#### Torch not support complex data type

In [133]:
a=t.eye(2)  # identity matrix
a

tensor([[1., 0.],
        [0., 1.]])

In [134]:
t.conjugate()

AttributeError: module 'torch' has no attribute 'conjugate'

## Cross Product
#### 3 column complsry

In [138]:
a=t.tensor([1,2])  # size 3 is complsry for cross product
b=t.tensor([3,4])  # 3 column is complsry
t.cross(a,b)

RuntimeError: no dimension of size 3 in input

In [142]:
a=t.tensor([1,2,3])  # same no of elmnt in both array, for cross product
b=t.tensor([4,5,6])  #2*6-3*5=-3, 3*4-1*6=6, 1*5-2*4=-3
t.cross(a,b)

tensor([-3,  6, -3])

In [144]:
a=t.tensor([[1,2,3],[4,5,6]])  # 1st array, 1st row cross product with 2nd array, 1st row
b=t.tensor([[7,8,9],[10,11,12]])  # 1st array, 2nd row with, 2nd array, 2nd row
t.cross(a,b)  # 2*9-3*8=-6, 3*7-1*9=12 , 6*10-4*12=12 like this we do

tensor([[-6, 12, -6],
        [-6, 12, -6]])

## Cumlative product

In [151]:
a=t.tensor([1,2,4])
a.cumprod(-1)  # o and -1 same axis bcoz its 1D tensor

tensor([1, 2, 8])

In [153]:
a.cumprod(0)

tensor([1, 2, 8])

In [159]:
# axis=1 means "Row wise"
a=t.tensor([[1,2,3],[4,5,6]])  # find same axis in any tensor/array  "axis-dimension" like  0-2 =-2, axis=0,-2 both r same axis
# t.cumprod(a,-1) # both r same
t.cumprod(a,1)  #there axis=1 also axis=-1 r also same, both have same output

tensor([[  1,   2,   6],
        [  4,  20, 120]])

In [161]:
# axis=0 means "column wise"
# t.cumprod(a,-2)
t.cumprod(a,0)  # there axis=0, also axis=-2 both have same output

tensor([[ 1,  2,  3],
        [ 4, 10, 18]])

In [171]:
c=t.tensor([[[1,2,3],[4,5,6]]])
c.cumprod(0)  # in this axis=0 means in 3D tensor is every elemnt self, so they start n end with himself , so got only same no

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [172]:
d=t.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d.cumprod(0)  # in this axis=0 means in 3D tensor is every elemnt self,there r 2 tensor in this, so they have start n end, so perfrom product with same index value

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7, 16, 27],
         [40, 55, 72]]])

In [174]:
# column wise   # same axis 1-3(bcoz 3D)=-2
print(c.cumprod(1))
c.cumprod(-2)

tensor([[[ 1,  2,  3],
         [ 4, 10, 18]]])


tensor([[[ 1,  2,  3],
         [ 4, 10, 18]]])

In [179]:
# row wsie    # same axis  2-3=-1
print(c.cumprod(2))
c.cumprod(-1)

tensor([[[  1,   2,   6],
         [  4,  20, 120]]])


tensor([[[  1,   2,   6],
         [  4,  20, 120]]])

## Diffrence (Diff)   # Pytroch not support
#### find out the diffrenc between 2 consecutive no next to each no

In [187]:
a=t.tensor([1,5,414,8,16,10])
t.diff(a)

AttributeError: module 'torch' has no attribute 'diff'

# inner   ( torch not support)

In [205]:
a=t.tensor([1,2,3])
b=t.tensor([4,5,6])
t.inner(a,b)

AttributeError: module 'torch' has no attribute 'inner'

# outer    ( Torch not suport)

In [1]:
a=t.tensor([1,2,3])
b=t.tensor([4,5,6])
t.outer(a,b)

NameError: name 't' is not defined

# Maximum (torch not support)

In [208]:
a=t.tensor([1,2,4,5,8])
a.maximum()

AttributeError: 'Tensor' object has no attribute 'maximum'

# Minimum (Torch not support)

In [209]:
a=t.tensor([1,2,4,5,8])
a.minimum()

AttributeError: 'Tensor' object has no attribute 'minimum'

# Covariance & Correlation Cofficient   ( Torch not support)

In [244]:
a=t.tensor([1,2,3],dtype=t.float)
b=t.tensor([4,5,6],dtype=t.float)
t.cov(a,b)

AttributeError: module 'torch' has no attribute 'cov'

In [245]:
a=t.tensor([1,2,3],dtype=t.float)
b=t.tensor([4,5,6],dtype=t.float)
t.corrcoef(a,b)

AttributeError: module 'torch' has no attribute 'corrcoef'

## Dot product
#### need same no of elemnt n Tensor data type data
#### only for 1D tensor (not work on 2D or 3D n others

In [193]:

a=t.tensor([1,2,3])
b=t.tensor([5,6,7])
print(t.dot(a,b))
a.dot(b)

tensor(38)


tensor(38)

In [200]:
a=t.tensor([[1,2]])
b=t.tensor([[7,8]])
a.dot(b)

RuntimeError: 1D tensors expected, got 2D, 2D tensors at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:774

## Mean
#### only support float data type

In [212]:
a=t.tensor([1,5,7,8,9,6],dtype=t.float)
a.mean()

tensor(6.)

In [218]:
b=t.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=t.float)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [220]:
b.mean()

tensor(5.)

In [222]:
# column wise
b.mean(axis=0)

tensor([4., 5., 6.])

In [224]:
# row wsie
b.mean(1)

tensor([2., 5., 8.])

## Median

In [226]:
a=t.tensor([1,6,6,3,1,8,9,25,30])
print(a)

tensor([ 1,  6,  6,  3,  1,  8,  9, 25, 30])


In [228]:
a.median()  # first sort the tensor thn even term so n=9 elmnt so (n+1)/2=5th value is our median

tensor(6)

In [230]:
b=t.tensor([[1,2,3],[4,5,6],[7,8,9]])
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [232]:
b.median()  # 9 elmnts so 5th value

tensor(5)

In [234]:
# column wise
b.median(axis=0)   # 3 value so 2nd value is out median of each column

torch.return_types.median(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [236]:
# row wise
b.median(axis=1)   # 3 value so 2nd value is out median of each row

torch.return_types.median(
values=tensor([2, 5, 8]),
indices=tensor([1, 1, 1]))