# Torch Indexing & slicing

In [1]:
import torch as t
import matplotlib.pyplot as plt

### indexing & slicing

In [2]:
a=t.arange(10)**3
a

tensor([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [3]:
a[0]  # indexing

tensor(0)

In [4]:
a[2:6]  # indexing n slicing 

tensor([  8,  27,  64, 125])

In [5]:
a[::2]  # extended slicing

tensor([  0,   8,  64, 216, 512])

In [6]:
a[-1:]

tensor([729])

In [7]:
a[-1:-3]

tensor([], dtype=torch.int64)

In [8]:
a[::-1]  # negative step not work

ValueError: negative step not yet supported

In [12]:
for i in a:
    print(i**(1/3))

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(3)
tensor(5)
tensor(5)
tensor(6)
tensor(7)
tensor(8)


In [14]:
b=t.arange(24).reshape(2,2,3,2)
b

tensor([[[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],

         [[ 6,  7],
          [ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15],
          [16, 17]],

         [[18, 19],
          [20, 21],
          [22, 23]]]])

In [15]:
b[0]

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [16]:
b[1]

tensor([[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

In [17]:
b[0,0]

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [18]:
b[0,1]

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [19]:
b[1,0]

tensor([[12, 13],
        [14, 15],
        [16, 17]])

In [20]:
b[1,1]

tensor([[18, 19],
        [20, 21],
        [22, 23]])

In [21]:
b.ndim

4

In [26]:
b[0][1][0]  # python indexing

tensor([6, 7])

In [24]:
b[0,1,0,0]  # fancy indexing

tensor(6)

In [28]:
b[1][0]

tensor([[12, 13],
        [14, 15],
        [16, 17]])

In [29]:
b[1][0][1:3]

tensor([[14, 15],
        [16, 17]])

In [30]:
b[1,0][1:3]

tensor([[14, 15],
        [16, 17]])

In [38]:
b[-1,-1]

tensor([[18, 19],
        [20, 21],
        [22, 23]])

In [43]:
a=b[0,0]<10
a

tensor([[True, True],
        [True, True],
        [True, True]])

In [44]:
c=b[0,0]>10
c

tensor([[False, False],
        [False, False],
        [False, False]])

In [45]:
a+c

tensor([[True, True],
        [True, True],
        [True, True]])

In [46]:
b[0:1,:-1]

tensor([[[[0, 1],
          [2, 3],
          [4, 5]]]])

## Fromfunction

In [33]:
def f(x,y):
    return x+y

b=t.fromfunction(f,(4,5))
b

AttributeError: module 'torch' has no attribute 'fromfunction'