# Torch

## Shape manipulation

In [2]:
import torch as t

In [18]:
a=t.floor(10*t.rand(3,4))
a

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

### cat

In [18]:
a=t.randn(3,3)
a

tensor([[-0.8682,  1.2504,  0.7225],
        [ 0.7153, -0.0713, -0.4683],
        [-0.1148, -0.4556, -0.0576]])

In [19]:
t.cat((a,a))  # print 2 times along with one bye one in # if we given 5 'a' , then got 5 a in same column

tensor([[-0.8682,  1.2504,  0.7225],
        [ 0.7153, -0.0713, -0.4683],
        [-0.1148, -0.4556, -0.0576],
        [-0.8682,  1.2504,  0.7225],
        [ 0.7153, -0.0713, -0.4683],
        [-0.1148, -0.4556, -0.0576]])

In [20]:
t.cat((a,a),axis=0)  # axis=0 means add a column wise

tensor([[-0.8682,  1.2504,  0.7225],
        [ 0.7153, -0.0713, -0.4683],
        [-0.1148, -0.4556, -0.0576],
        [-0.8682,  1.2504,  0.7225],
        [ 0.7153, -0.0713, -0.4683],
        [-0.1148, -0.4556, -0.0576]])

In [21]:
t.cat((a,a),axis=1)  # print array in row wsie means both array 1st row in 1row, 2nd in 2nd, 3rd in 3r row concat

tensor([[-0.8682,  1.2504,  0.7225, -0.8682,  1.2504,  0.7225],
        [ 0.7153, -0.0713, -0.4683,  0.7153, -0.0713, -0.4683],
        [-0.1148, -0.4556, -0.0576, -0.1148, -0.4556, -0.0576]])

### reshape()

In [19]:
a.reshape(4,3)  # not changed original data

tensor([[8., 8., 1.],
        [5., 7., 0.],
        [3., 9., 7.],
        [3., 4., 6.]])

In [20]:
a    # a is not affected by reshape()

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

In [21]:
a.shape

torch.Size([3, 4])

### view()

In [54]:
a.view(-1)

tensor([8., 8., 1., 5., 7., 0., 3., 9., 7., 3., 4., 6.])

In [22]:
a.view(4,3)  # view not changed original data

tensor([[8., 8., 1.],
        [5., 7., 0.],
        [3., 9., 7.],
        [3., 4., 6.]])

In [23]:
a  # data not affected by "view"

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

### unsqueeze()

In [35]:
a.unsqueeze(0)  # not changed the original data

tensor([[[8., 8., 1., 5.],
         [7., 0., 3., 9.],
         [7., 3., 4., 6.]]])

In [36]:
a.unsqueeze(1)

tensor([[[8., 8., 1., 5.]],

        [[7., 0., 3., 9.]],

        [[7., 3., 4., 6.]]])

In [37]:
a.unsqueeze(2)

tensor([[[8.],
         [8.],
         [1.],
         [5.]],

        [[7.],
         [0.],
         [3.],
         [9.]],

        [[7.],
         [3.],
         [4.],
         [6.]]])

In [41]:
a     # original data not changed by "unsqueeze"

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

### resize()

In [59]:
a.resize(2,2,3)   # not chnaged the original data

c:\users\patid\appdata\local\programs\python\python37\lib\site-packages\torch\tensor.py:314: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[[8., 8., 1.],
         [5., 7., 0.]],

        [[3., 9., 7.],
         [3., 4., 6.]]])

In [60]:
a  # not effect by "resize"

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

## ravel()  ( torch not support )
#### view(-1)   do the same

In [61]:
a.ravel()

AttributeError: 'Tensor' object has no attribute 'ravel'

## flatten()

In [62]:
a.flatten()  # not affect original data

tensor([8., 8., 1., 5., 7., 0., 3., 9., 7., 3., 4., 6.])

In [64]:
a        # not affected by " flatten "

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

In [74]:
c=t.tensor([[1,2],[3,4]])
print(c)

tensor([[1, 2],
        [3, 4]])


In [75]:
c.flatten()

tensor([1, 2, 3, 4])

In [76]:
c.flatten("C")

TypeError: flatten(): argument 'start_dim' (position 1) must be int, not str

In [78]:
c.flatten(0)

tensor([1, 2, 3, 4])

In [79]:
c.flatten(1)

tensor([[1, 2],
        [3, 4]])

#### when we store reshape output into another variable  then data is changed and store in another variable but our roginal data in which variavle have not changed

In [67]:
c=a.reshape(6,2)
c

tensor([[8., 8.],
        [1., 5.],
        [7., 0.],
        [3., 9.],
        [7., 3.],
        [4., 6.]])

In [68]:
a  # but original data is same

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

### tranpose()

In [69]:
a.T

tensor([[8., 7., 7.],
        [8., 0., 3.],
        [1., 3., 4.],
        [5., 9., 6.]])

In [70]:
a

tensor([[8., 8., 1., 5.],
        [7., 0., 3., 9.],
        [7., 3., 4., 6.]])

In [73]:
a.transpose(0,1)  # row row n column is replace
# axis 0(column) replace woth axis 1(column)

tensor([[8., 7., 7.],
        [8., 0., 3.],
        [1., 3., 4.],
        [5., 9., 6.]])

### transpose like operator

In [83]:
a=t.zeros(3,4,5)
a

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [85]:
a=t.zeros([3,4,5])
a

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [86]:
a.shape

torch.Size([3, 4, 5])

In [89]:
t.moveaxis()

AttributeError: module 'torch' has no attribute 'moveaxis'

In [3]:
t.swapaxes()

AttributeError: module 'torch' has no attribute 'swapaxes'

## stacking together diff array

In [92]:
a=t.rand(2,2)
a

tensor([[0.2150, 0.0350],
        [0.7133, 0.7917]])

In [9]:
a=t.floor(10*t.rand(2,2))
a

tensor([[9., 4.],
        [6., 0.]])

In [10]:
b=t.floor(t.rand(2,2)*10)
b

tensor([[2., 6.],
        [9., 4.]])

### stack

In [101]:
t.stack([a,b])

tensor([[[9., 1.],
         [4., 9.]],

        [[8., 2.],
         [1., 8.]]])

In [103]:
t.stack([a,b],0)

tensor([[[9., 1.],
         [4., 9.]],

        [[8., 2.],
         [1., 8.]]])

In [104]:
t.stack([a,b],1)

tensor([[[9., 1.],
         [8., 2.]],

        [[4., 9.],
         [1., 8.]]])

In [105]:
t.stack([a,b],2)  # put each tensor as a column
# tensor a is 1st column, tensor b is nd column

tensor([[[9., 8.],
         [1., 2.]],

        [[4., 1.],
         [9., 8.]]])

### vstack

In [11]:
t.vstack(a,b)

AttributeError: module 'torch' has no attribute 'vstack'

In [13]:
t.hstack(a,b)

AttributeError: module 'torch' has no attribute 'hstack'

In [14]:
t.column_stack(a,b)

AttributeError: module 'torch' has no attribute 'column_stack'

In [15]:
a=t.tensor([2,4])
a

tensor([2, 4])

In [16]:
a[:,newaxis]

NameError: name 'newaxis' is not defined

In [17]:
t.dstack()

AttributeError: module 'torch' has no attribute 'dstack'