# Torch tensor manipulation

In [1]:
import torch as t

In [4]:
t.r_()  # row concate 

AttributeError: module 'torch' has no attribute 'r_'

In [5]:
t.c_()   # column concate

AttributeError: module 'torch' has no attribute 'c_'

## Split

In [18]:
a=t.arange(1,17).view(4,4)  # .reshape do also same
a

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [12]:
t.split(a,1)  # take each 1 row n split into diffrent tensor  # total 4 row so 4 tensor 

(tensor([[1, 2, 3, 4]]),
 tensor([[5, 6, 7, 8]]),
 tensor([[ 9, 10, 11, 12]]),
 tensor([[13, 14, 15, 16]]))

In [13]:
t.split(a,2)   # take each 2 row n split into diffrent tensor  # total 4 row so we got 2 tensor each has 2 rows tensor 

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]), tensor([[ 9, 10, 11, 12],
         [13, 14, 15, 16]]))

In [14]:
t.split(a,3)    # take each 3 row n split into diffrent tensor  # total 4 row so we got 2 tensor, 1st have 3rows and 2nd have only 1 row bcoz we have only 4 rows so remaining in last tensor if we have not enough split for last tensor tensor 

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]), tensor([[13, 14, 15, 16]]))

In [15]:
t.split(a,4)     # take each 4 row n split into diffrent tensor  # total 4 row so we got 1 tensor of 4 rows tensor 

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),)

In [16]:
t.split(a,5)    # take each 5 row n split into diffrent tensor but e have only 4 rows so it take 4 rows n kame a new tensor

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),)

## split_with_sizes
#### size of tuple is like (x,y) is equal to the sum of rows no

In [26]:
t.split_with_sizes(a,(1,3))

(tensor([[1, 2, 3, 4]]), tensor([[ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]))

In [27]:
t.split_with_sizes(a,(2,2))

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]), tensor([[ 9, 10, 11, 12],
         [13, 14, 15, 16]]))

In [32]:
a=t.arange(24).view(6,4)  # .reshape do also same
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

In [39]:
t.split_with_sizes(a,(3,3))  # (3,3) is tuple n additon is equal to the total no of rows

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]), tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]))

In [40]:
t.split_with_sizes(a,(1,5))

(tensor([[0, 1, 2, 3]]), tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]))

In [41]:
t.split_with_sizes(a,(5,1))

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]), tensor([[20, 21, 22, 23]]))

## Hsplit &  Dsplit ( Torch not support both)

In [42]:
a=t.arange(24).reshape(2,2,6)
a

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])

In [43]:
t.hsplit(a)

AttributeError: module 'torch' has no attribute 'hsplit'

In [44]:
t.dsplit(a)

AttributeError: module 'torch' has no attribute 'dsplit'