# Universal Functions

In [1]:
import torch as t

In [4]:
a=t.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [6]:
c=t.empty(2,2)
c

tensor([[0., 0.],
        [0., 0.]])

In [5]:
a=t.empty(2,3)
t.ones_like(a)  # a must be input type tensor not look like ones_like(2,3) not valid

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
b=t.zeros(3,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
a=t.zeros(2,3)
t.zeros_like(a)  ## a must be input type tensor not look like ones_like(2,3) not valid

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
d=t.eye(3)
d

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
e=t.rand((2,2))
e

tensor([[0.6794, 0.5632],
        [0.4342, 0.5109]])

In [24]:
f=t.randn(3,3)
f

tensor([[-0.5156,  0.7939, -0.0051],
        [-0.0139, -1.1555,  0.9836],
        [ 0.9459,  1.9824,  1.5583]])