In [1]:
import torch as t

## as_tensor

In [126]:
a=t.tensor([2,5,6,9])
a

tensor([2, 5, 6, 9])

In [127]:
b=t.as_tensor(a)
b

tensor([2, 5, 6, 9])

In [128]:
b is a  # same memory refrence

True

In [129]:
b[0]=10
b

tensor([10,  5,  6,  9])

In [130]:
a   # 'a' value is also chnged bcoz  same memory refrence

tensor([10,  5,  6,  9])

## normal copy

In [2]:
a=t.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b=a
b

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b is a

True

In [5]:
c=[1,2,3]
d=[1,2,3]
c is d

False

In [6]:
a.shape

torch.Size([12])

In [7]:
b.shape

torch.Size([12])

In [12]:
a.reshape(2,2,3)   # a original data not changed

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [18]:
a=t.arange(12).reshape(3,2,2)
a

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [19]:
b=a
b

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

#### now we make changed into array

In [30]:
b[0]=10  # tensor not take b[0]=10,20 like 'Numpy'  # take only one value n make changed into tensor
b #we make changes into b

tensor([[[10, 10],
         [10, 10]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [32]:
a    # see 'a' is also changed bcoz of we make changes in "b", both pointed same memoryt refrence so

tensor([[[10, 10],
         [10, 10]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [34]:
b is a  # this reason make chnges in one effect the other

True

In [36]:
a[0,:]

tensor([[10, 10],
        [10, 10]])

## view or shallow copy

In [37]:
a

tensor([[[10, 10],
         [10, 10]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [40]:
c=a.view(3,2,2)  # view used for reshape tensor
c

tensor([[[10, 10],
         [10, 10]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [41]:
c is a  # both have not same meory refrence but they both r same value

False

In [48]:
# now we make chnged into c
c[0]=25
c  # c value changed

tensor([[[25, 25],
         [25, 25]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [50]:
a           # a value is also chnged

tensor([[[25, 25],
         [25, 25]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [52]:
b      # b value is also changed

tensor([[[25, 25],
         [25, 25]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [88]:
s=a[:,1:3]        # indexing n slicing both # (3,2,2) shape so indexing is like this [ : , : , : ] for this
s           # [:] all array  [1:3] only 1st n 2nd row all the elmnt bcoz no column define  # there r only 1st index row

tensor([[[25, 25]],

        [[ 6,  7]],

        [[10, 11]]])

In [85]:
s=a[:,1:3,0:1]   # its indexing n slicing for 3d tensor
s

tensor([[[25]],

        [[ 6]],

        [[10]]])

In [92]:
# now we make chnge in s
s[:]=100
s

tensor([[[100, 100]],

        [[100, 100]],

        [[100, 100]]])

In [93]:
a  # make chnged in 's' effect the data of 'a'

tensor([[[ 25,  25],
         [100, 100]],

        [[  4,   5],
         [100, 100]],

        [[  8,   9],
         [100, 100]]])

In [94]:
b     # make chnged in 's' effect the data of 'b'

tensor([[[ 25,  25],
         [100, 100]],

        [[  4,   5],
         [100, 100]],

        [[  8,   9],
         [100, 100]]])

In [95]:
c    # make chnged in 's' effect the data of 'c'

tensor([[[ 25,  25],
         [100, 100]],

        [[  4,   5],
         [100, 100]],

        [[  8,   9],
         [100, 100]]])

## deep copy  ( clone )
#### clone not effect the oroginal data

In [98]:
a=t.arange(1,13).view(3,2,2)
a

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [101]:
# make a deep copy
d=a.clone()
d

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [102]:
d is a

False

In [104]:
a

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [105]:
# make chnged into d
d[0,0]=999
d

tensor([[[999, 999],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]],

        [[  9,  10],
         [ 11,  12]]])

In [107]:
a             # original data not effected

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

# Fill the data

In [111]:
a.data.fill_(25)  # all data is fill with 25

tensor([[[25, 25],
         [25, 25]],

        [[25, 25],
         [25, 25]],

        [[25, 25],
         [25, 25]]])

## conversion

In [112]:
a.type(t.float)

tensor([[[25., 25.],
         [25., 25.]],

        [[25., 25.],
         [25., 25.]],

        [[25., 25.],
         [25., 25.]]])

In [116]:
a.type(t.long)

tensor([[[25, 25],
         [25, 25]],

        [[25, 25],
         [25, 25]],

        [[25, 25],
         [25, 25]]])

In [118]:
a.type(t.bool)

tensor([[[True, True],
         [True, True]],

        [[True, True],
         [True, True]],

        [[True, True],
         [True, True]]])

In [119]:
a.type(t.double)

tensor([[[25., 25.],
         [25., 25.]],

        [[25., 25.],
         [25., 25.]],

        [[25., 25.],
         [25., 25.]]], dtype=torch.float64)

## atleast_2d n more   ( torch not support)

In [120]:
t.atleast_2d()

AttributeError: module 'torch' has no attribute 'atleast_2d'

In [121]:
t.atleast_3d()

AttributeError: module 'torch' has no attribute 'atleast_3d'

In [123]:
t.mat(a)

AttributeError: module 'torch' has no attribute 'mat'

In [124]:
t.asmatrix(a)

AttributeError: module 'torch' has no attribute 'asmatrix'

In [125]:
t.as_tensor(a)

tensor([[[25, 25],
         [25, 25]],

        [[25, 25],
         [25, 25]],

        [[25, 25],
         [25, 25]]])