In [1]:
import torch as t
import matplotlib.pyplot as plt
import numpy as np

In [3]:
a=t.arange(4)
a

tensor([0, 1, 2, 3])

In [4]:
b=a.reshape(4,1)
b

tensor([[0],
        [1],
        [2],
        [3]])

In [6]:
c=t.ones(5)
c

tensor([1., 1., 1., 1., 1.])

In [8]:
d=t.ones(3,4)
d

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
a.shape  # 1D vector so total no of element is the shape [4] total 4 elements

torch.Size([4])

In [10]:
b.shape

torch.Size([4, 1])

In [11]:
c.shape

torch.Size([5])

In [12]:
d.shape

torch.Size([3, 4])

In [ ]:
def solve (query, arr):
    # Your Code Here
    print(arr)

n = int(input())
arr = map(int, input().split())
Q = int(input())
col = 2
query = []
for _ in range(Q):
    query.append(map(int, input().split()))

out_ = solve(query, arr)
for i_out_ in out_:
    print (' '.join(map(str, i_out_)))

 5
